### PR TITLE
Clarify contribution licensing requirement (close #28)

### LINKED ISSUE #28: Is there missing something?
Hi there,

this might very well be just my brain knotting up, but when reading over: 

> To contribute software, publish all its source code, in the
> preferred form for making changes, through a freely accessible
> distribution system widely used for similar source code, and
> license contributions not already licensed to the public on terms
> as permissive as this license accordingly.

I feel there is a slight gap somewhere. I have a hard time explaining myself though. 

Which part does the 'on terms as permissive as this license accordingly' belong to? To 'not already licensed', or 'license contributions'?

Does it tell me to 'license contributions':

- which are not licensed in terms as permissive...

or

- (any contributions that are not already licensed to the public) in a way (on terms) that they are licensed as permissive...

I guess the former, as the 'on' makes less sense otherwise (but I'm not sure, that's where I have an English-as-a-second-language problem, as well as with 'accordingly', as I'm not sure what exactly that refers to. So mabye it's very clear to a native speaker, if that's the case just ignore me.

Either way, if the former, couldn't I choose to license any old way (even less permissive), as long as I license parts that are not licensed at all to the public yet? Or does the accordingly here prevent that? If, is that a strong enough marker?

And if the latter, what about parts that are already licensed to the public?

Does any of this make sense? :-)

P.S. I've read your latest blog post, but didn't get any more clarity on that one point there either...

### PR DESCRIPTION
**Pull request by kemitchell**
Turning my proposal in https://github.com/licensezero/parity-public-license/issues/28#issuecomment-518863557 into a PR. 

@jeremy-w, @makkus, @mlinksva: Is this easier to read, from your point of view?

If so, we have to ask where this takes us. Patch release? Batch it up with #47 and #48?

### CODE REVIEW

**Comment by mlinksva** [comment]
Yes, this is easier to read.

Seems fine to me to make patch release and batch with #47 and #48. Unless #48 merits a bump greater than patch, though batch would still make sense.

**Comment by kemitchell** [comment]
@mlinksva part of it is what makes sense, versioning-wise.  Part of it is deciding whether and when to go back to SPDX for a new version. That's easy for me to do, but it takes time, and we don't want to disrespect that team's time.

**Comment by makkus** [comment]
This is perfect, No ambiguity at all anymore (for me, anyway).

**Comment by kemitchell** [comment]
Prior comments mentioned that "as permissive as" could be confusing, since Parity is, in the jargon, a very strong copyleft license, as _distinct_ from a permissive license.

**Comment by kemitchell** [comment]
Prior comments mentioned that "as permissive as" could be confusing, since Parity is, in the jargon, a very strong copyleft license, as _distinct_ from a permissive license.

**Comment by kemitchell** [comment]
This feedback---though not this exact language---was included in the rewrite for version 7.0.0.

Currently on master (261b2356ebb687b96b8cbb7dd7a90e825b6e014c):

> ## Contributing
> 
> When this license requires you to contribute:
> 
> 1.  Publish all source code, in the preferred form for making changes, through a freely accessible distribution system widely used for similar source code, so the contributor and others can find and copy it.
> 
> 2.  Ensure that each part of that source code is available to the public under a license at least as permissive as this one, such as MIT, two-clause BSD license, Apache 2.0, or Blue Oak Model 1.0.0.
> 
> 3.  Take these steps within thirty calendar days of when you first did anything requiring contribution.
> 
> Note that this license does _not_ allow you to change the license terms for this software.

**Pull request closed without merging**
