### PR TITLE
Rule 2: Prefer “project” to “app”, “entire” to “larger”

### PR DESCRIPTION
**Pull request by jeremy-w**
h/t @makkus
https://github.com/licensezero/parity-public-license/issues/30#issuecomment-444794274

[#30]

### CODE REVIEW

**Comment by kemitchell** [comment]
"larger application" also appears in Rule 5.

**Comment by kemitchell** [comment]
@jeremy-w This all looks good to me now. I want to take a little more time to forget about the license, so I can come back to it fresh and review one more time.

There's no strict versioning scheme for Parity, but my gut tells me this would be a 6.0.0.

**Comment by kemitchell** [comment]
@jeremy-w, thanks for your patience. As you've probably come to suspect, I've got a few projects begging for my time, work included.

I think the thrust of this change is 100% correct. The word "application" is either broader or narrower than "program", depending on context. Parity needs words that sweep its copyleft requirement broadly than narrow readings of "program". In all contexts.

The trouble with "project" is that it focuses on how software is made, rather than the functionality, novelty, or distinctiveness of software once it is made. For example, depending on the point of view of the developer, creating a package implementing authentication for web apps might very well count as a substantial project, in and of itself. But Parity's copyleft rule aims to sweep not just that package, but web apps that incorporate it.

I think "application" in its original sense most directly to this concept: If you apply the Parity code to address a different or broader problem, release all of that. But your note on the narrower use of "application", in particular as a contraction of "application", is accurate and important.

I have some thinking to do.

**Comment by kemitchell** [comment]
@jeremy-w, thanks for your patience! This remains a really great pull request. It's been gnawing on me since you sent it!

I believe I've finally stumbled on the insight that feels _right_: There is _no word_ like "application" or "project" or "program", equally general across all of software, but more specific.

The upshot: Just say "software". Don't rely so heavily on an extra word that only drains clarity.

> 2. If you run or combine this software with other software, contribute that software.

I have this change, along with a conforming change in rule 5, in 4d07aef73c15c49fab9dc82fc712dddacd2ed5c2, a child of your PR commit.

I'd love to read your thoughts on this!

**Comment by jeremy-w** [comment]
I think that makes a lot of sense. It also avoids adding another term to the mix.

I've left some comments on the commit with my thoughts on the details of the proposed change itself.

**Comment by kemitchell** [comment]
@jeremy-w Thanks so much for attention and comments. I am going to merge this now, but not release a new version until I have a think about your concerns in current Rule 2.

**Pull request merged**
