### PR TITLE
Simplify Copyleft

### PR DESCRIPTION
**Pull request by kemitchell**
This PR begins the process of simplifying the copyleft rules. The major insight here is that old rules 1 (changes, additions) and 2 (combinations) were really just special cases of rule 3 (develop, deploy, monitor, run).

The new copyleft rule focuses in on old rule 3. I am still interested in finding an abstraction that covers "develop, deploy, monitor, or run". Other folks have posted great links to various overviews of the "dev ops" lifecycle.

### CODE REVIEW

**Comment by kemitchell** [comment]
I suppose the fundamental insight of the devops abstractions we've discussed is a conjunction of _development_ and _operation_, where operation encomapsses deploying, running, monitoring, &c. Which begs the question:

> ## Copyleft
>
> Contribute software that you develop or operate with this software, including changed or extended versions of this software. ...

**Comment by makkus** [comment]
I really like this simplified version. Something in the back of my mind tells me it can't be possibly that easy, but I can't see anything wrong with it...

**Comment by kemitchell** [comment]
@makkus this is why we have test suites! https://github.com/licensezero/parity-public-license/pull/61/files#diff-f7dc5cbdfcf7d6d5c4094a19b743219b. Haven't gone through and actually "run" that suite systematically yet. But I want to start tracking it in the repo.

By the way, do you see a reason to stick with "develop, deploy, monitor, run", or does "develop or operate" cover it?

**Comment by makkus** [comment]
Oh, neat. Did not see those tests yet. And no, for my personal use cases, I think 'develop' and 'operate' should cover the use-cases I want to have covered.

**Comment by kemitchell** [comment]
@makkus: Correct. The idea behind the "test suite" was to imagine that each project were licensed under Parity.

**Comment by makkus** [comment]
| 'changed or extended'

Is 'extended' necessary? Even though it has a slightly different meaning, wouldn't that be covered by 'operate'?

**Comment by makkus** [comment]
I've tried to come up with a test case for Ansible, and I'm not 100% sure 'operate' would be the perfect fit for all cases (feel free to add this to the test suite if you think it makes sense):

Ansible:
- Ansible roles
- Ansible modules
- software deployed

The problem I'm having is with the roles and modules, as they are sort of 'plugins' for Ansible, and they only play a role in the 'deploy' step, but they are not themselves deployed. The old 'run' would be a fit, because they are run from Ansible. But, as I said, I don't think 'operate' fits quite right.

**Comment by kemitchell** [comment]
@makkus I'm afraid I don't know Ansible terminology very well. The same goes for Chef, which is in my test suite.

Are roles and modules "software"?

**Comment by makkus** [comment]
Yes, both are software I'd say. "modules" definitely, they are just Python files that are used in the context of a provisioning run. They sort of deal with the low-level tasks like creating folders, or users, or talking to an API and such.  

Roles are collections of (mostly) yaml files, which collect a succession of calls to modules to do some higher level things (like setting up a Wordpress server or similar). Even though they are yaml, I'm pretty sure they'd count as software, they are basically structured lists of instructions.

**Pull request merged**
